# -*- coding: utf-8 -*-
"""final code research seminar RP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Qdaiig5pG1nfM2Ztq6G37FfTBk8H4p5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from tensorflow.keras.datasets import mnist

#Load MNIST ONCE
def load_mnist_vectors():
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train = x_train.reshape(-1, 784) / 255.0
    x_test  = x_test.reshape(-1, 784) / 255.0
    return x_train, y_train, x_test, y_test

X_TRAIN_ALL, Y_TRAIN_ALL, X_TEST_ALL, Y_TEST_ALL = load_mnist_vectors()

#Filter digits
def get_filtered_data(d1, d2):
    mask_train = (Y_TRAIN_ALL == d1) | (Y_TRAIN_ALL == d2)
    mask_test  = (Y_TEST_ALL == d1)  | (Y_TEST_ALL == d2)

    x_train_f = X_TRAIN_ALL[mask_train]
    y_train_f = (Y_TRAIN_ALL[mask_train] == d2).astype(int)

    x_test_f  = X_TEST_ALL[mask_test]
    y_test_f  = (Y_TEST_ALL[mask_test] == d2).astype(int)

    return x_train_f, y_train_f, x_test_f, y_test_f

#visualization
def show_me_the_matrix(inputvec):
    plt.matshow(inputvec.reshape(28,28))
    plt.colorbar()
    plt.title("Model Weights Visualization")
    plt.show()

def train_logistic(x, y, C):
    clf = LogisticRegression(C=C, max_iter=2000)
    clf.fit(x, y)
    return clf

def train_svm(x, y, C):
    clf = LinearSVC(C=C, max_iter=5000)
    clf.fit(x, y)
    return clf

#Random subspace
def random_k_subspace(d, k):
    basis = np.random.randn(d, k)
    Q, _ = np.linalg.qr(basis)
    return Q

def baseline(d1, d2, model, C):

    x_train_f, y_train_f, x_test_f, y_test_f = get_filtered_data(d1, d2)

    if model == "LogReg":
       clf = train_logistic(x_train_f, y_train_f, C)
    else:
        clf = train_svm(x_train_f, y_train_f, C)

    acc = np.mean(clf.predict(x_test_f) == y_test_f)
    print(f"Baseline accuracy: {acc:.4f}")

    return clf

def track_iterations(d1, d2, k, iterations, model, C, corruption=0.0):

    x_train_f, y_train_f, x_test_f, y_test_f = get_filtered_data(d1, d2)

    idx = np.random.choice(len(x_train_f), 500, replace=False)
    x_train = x_train_f[idx]
    y_train = y_train_f[idx]

    n_corrupt = int(corruption * len(y_train))
    if n_corrupt > 0:
        corrupt_idx = np.random.choice(len(y_train), n_corrupt, replace=False)
        y_train[corrupt_idx] = 1 - y_train[corrupt_idx]

    train_accs = []
    test_accs = []

    for i in range(iterations):
        Q = random_k_subspace(784, k)

        x_train_proj = x_train @ Q
        x_test_proj  = x_test_f @ Q

        if model == "LogReg":
            clf = train_logistic(x_train_proj, y_train, C)
        else:
            clf = train_svm(x_train_proj, y_train, C)

        train_accs.append(np.mean(clf.predict(x_train_proj) == y_train))
        test_accs.append(np.mean(clf.predict(x_test_proj) == y_test_f))

    return train_accs, test_accs

#Ensemble experiment
def run_single_experiment(x_train_f, y_train_f, x_test_f, y_test_f,
                         k, corruption, model, C,
                         subset_size=500, n_models=5):

    #Copy to avoid modifying global data
    x_train = x_train_f.copy()
    y_train = y_train_f.copy()

    #Subsample
    idx = np.random.choice(len(x_train), subset_size, replace=False)
    x_train = x_train[idx]
    y_train = y_train[idx]

    #Corrupt labels
    n_corrupt = int(corruption * len(y_train))
    if n_corrupt > 0:
        corrupt_idx = np.random.choice(len(y_train), n_corrupt, replace=False)
        y_train[corrupt_idx] = 1 - y_train[corrupt_idx]

    train_preds = []
    test_preds = []

    for _ in range(n_models):
        Q = random_k_subspace(784, k)

        x_train_proj = x_train @ Q
        x_test_proj  = x_test_f @ Q

        if model == "LogReg":
            clf = train_logistic(x_train_proj, y_train, C)
        else:
            clf = train_svm(x_train_proj, y_train, C)

        train_preds.append(clf.predict(x_train_proj))
        test_preds.append(clf.predict(x_test_proj))

    #Majority vote
    train_preds = np.array(train_preds)
    test_preds  = np.array(test_preds)

    train_final = (np.mean(train_preds, axis=0) > 0.5).astype(int)
    test_final  = (np.mean(test_preds, axis=0) > 0.5).astype(int)

    train_acc = np.mean(train_final == y_train)
    test_acc  = np.mean(test_final == y_test_f)
    gap = train_acc - test_acc

    return train_acc, test_acc, gap

#Grid experiment
def run_grid(d1, d2, k_values, corruption_levels, models, C_values,
             n_runs=20, subset_size=500, n_models=5):

    x_train_f, y_train_f, x_test_f, y_test_f = get_filtered_data(d1, d2)

    results = []

    for model in models:
        for C in C_values:
            for corr in corruption_levels:
                for k in k_values:

                    train_scores = []
                    test_scores = []
                    gaps = []

                    for _ in range(n_runs):
                        tr, te, gap = run_single_experiment(
                            x_train_f, y_train_f,
                            x_test_f, y_test_f,
                            k, corr, model, C,
                            subset_size, n_models
                        )
                        train_scores.append(tr)
                        test_scores.append(te)
                        gaps.append(gap)

                    results.append({
                        "model": model,
                        "C": C,
                        "corruption": corr,
                        "k": k,
                        "train_mean": np.mean(train_scores),
                        "test_mean": np.mean(test_scores),
                        "gap_mean": np.mean(gaps),
                        "train_std": np.std(train_scores),
                        "test_std": np.std(test_scores),
                        "gap_std": np.std(gaps)
                    })

                    print(f"{model} | C={C} | corr={corr} | k={k} done")

    return pd.DataFrame(results)

#Heatmaps
def plot_heatmap(df, model, C, value, title):
    subset = df[(df["model"] == model) & (df["C"] == C)]
    pivot = subset.pivot(index="corruption", columns="k", values=value)

    plt.figure()
    plt.imshow(pivot, aspect='auto')
    plt.colorbar()
    plt.xticks(range(len(k_values)), k_values)
    plt.yticks(range(len(corruption_levels)), corruption_levels)
    plt.xlabel("k (dimension)")
    plt.ylabel("corruption")
    plt.title(title)
    plt.show()

#baseline
clf = baseline(d1=3, d2=8, model="LogReg", C=1.0)
show_me_the_matrix(clf.coef_[0])

#graphs for differnt, models, corruption levels, and k
k_values = [5, 10, 20]
corruption_levels = [0.0, 0.1, 0.2, 0.3, 0.4]
models = ["SVM", "LogReg"]

iterations = 100

for model in models:
    for corruption in corruption_levels:
        for k in k_values:

            train_accs, test_accs = track_iterations(
                d1=3,
                d2=8,
                k=k,
                iterations=iterations,
                model=model,
                C=1.0,
                corruption=corruption
            )

            plt.figure(figsize=(10, 6))
            plt.plot(range(iterations), train_accs, label="Training Accuracy")
            plt.plot(range(iterations), test_accs, label="Test Accuracy")

            plt.xlabel("Iteration")
            plt.ylabel("Accuracy")
            plt.title(f"{model} | k={k} | corruption={corruption}")
            plt.legend()
            plt.grid(True)
            plt.ylim(0, 1)

            plt.show()

k_values = [2, 5, 10, 20, 50]
corruption_levels = [0.0, 0.1, 0.2, 0.3, 0.4]
models = ["LogReg", "SVM"]
C_values = [0.1, 1.0]

df = run_grid(
    d1=3, d2=8,
    k_values=k_values,
    corruption_levels=corruption_levels,
    models=models,
    C_values=C_values,
    n_runs=20, # Increased n_runs to 20
    subset_size=500,
    n_models=5
)

print(df)

#heatmaps
for model in models:
    for C in C_values:
        plot_heatmap(df, model, C, "test_mean",
                     f"{model} (C={C}) Test Accuracy")

        plot_heatmap(df, model, C, "gap_mean",
                     f"{model} (C={C}) Train-Test Gap")

display(df)

# Ensure df is defined. If this cell is run independently, df might not exist.
# The df is typically generated by the 'run_grid' function in cell 'sJQcLAuAQ3vt'.
# To avoid NameError if 'sJQcLAuAQ3vt' was not run, we can re-run the grid experiment here.
try:
    df.head() # Try to access df to see if it exists
except NameError:
    print("DataFrame 'df' not found in current scope. Re-running the grid experiment to define it.")
    # Parameters for run_grid from cell sJQcLAuAQ3vt
    k_values = [2, 5, 10, 20, 50]
    corruption_levels = [0.0, 0.1, 0.2, 0.3, 0.4]
    models = ["LogReg", "SVM"]
    C_values = [0.1, 1.0]

    df = run_grid(
        d1=3, d2=8,
        k_values=k_values,
        corruption_levels=corruption_levels,
        models=models,
        C_values=C_values,
        n_runs=3,
        subset_size=500,
        n_models=5
    )

# Aggregate the results by model, C, and corruption for mean test_mean
agg_df = df.groupby(['model', 'C', 'corruption'])['test_mean'].mean().reset_index()

plt.figure(figsize=(12, 7))
sns.lineplot(data=agg_df, x='corruption', y='test_mean', hue='model', style='C', marker='o')

plt.title('Average Test Accuracy Degradation vs. Corruption Level')
plt.xlabel('Corruption Level')
plt.ylabel('Average Test Accuracy')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Model and C Value')
plt.ylim(0.5, 1.0) # Set a reasonable y-axis limit
plt.show()

#GAP vs corruption plot (H1)
plt.figure(figsize=(12, 7))

sns.lineplot(
    data=df,
    x='corruption',
    y='gap_mean',
    hue='model',
    style='C',
    marker='o'
)

plt.title('Train-Test Gap vs. Corruption Level ')
plt.xlabel('Corruption Level')
plt.ylabel('Train - Test Accuracy Gap')
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

"""### Train-Test Gap for Logistic Regression"""

plt.figure(figsize=(12, 7))

# Filter for Logistic Regression only
logreg_df = df[df['model'] == 'LogReg']

sns.lineplot(
    data=logreg_df,
    x='corruption',
    y='gap_mean',
    hue='k', # Use k as hue to see its effect
    style='C', # Use C as style
    marker='o'
)

plt.title('LogReg Train-Test Gap vs. Corruption Level by k and C')
plt.xlabel('Corruption Level')
plt.ylabel('Train - Test Accuracy Gap')
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

"""### Train-Test Gap for Support Vector Machines"""

plt.figure(figsize=(12, 7))

# Filter for SVM only
svm_df = df[df['model'] == 'SVM']

sns.lineplot(
    data=svm_df,
    x='corruption',
    y='gap_mean',
    hue='k', # Use k as hue to see its effect
    style='C', # Use C as style
    marker='o'
)

plt.title('SVM Train-Test Gap vs. Corruption Level by k and C')
plt.xlabel('Corruption Level')
plt.ylabel('Train - Test Accuracy Gap')
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

"""### Direct Comparison: SVM vs. LogReg Train-Test Gap"""

# Create a FacetGrid to plot 'gap_mean' for both models side-by-side
# 'col' creates separate plots for each 'k' value
# 'hue' distinguishes between 'model' (LogReg vs. SVM)
# 'style' distinguishes between 'C' values
g = sns.FacetGrid(df, col='k', hue='model', style='C', col_wrap=3, height=4, aspect=1.2)

# Map the lineplot function onto the grid
g.map(sns.lineplot, 'corruption', 'gap_mean', marker='o')

# Add titles and labels
g.set_axis_labels('Corruption Level', 'Train - Test Accuracy Gap')
g.set_titles('k = {col_name}')
g.add_legend(title='Model / C Value')

plt.suptitle('Train-Test Gap: SVM vs. Logistic Regression Across k and C', y=1.02) # Add a main title
plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent title overlap
plt.show()

"""### Average Train-Test Gap for Logistic Regression"""

try:
    logreg_avg_gap = df[df['model'] == 'LogReg']['gap_mean'].mean()
    print(f"Average Train-Test Gap for Logistic Regression across all parameters: {logreg_avg_gap:.4f}")
except NameError:
    print("DataFrame 'df' not found. Please ensure the 'run_grid' cell (sJQcLAuAQ3vt) or (ce400372) has been executed to generate the DataFrame.")

highest_corruption_level = df['corruption'].max()
high_corruption_results = df[df['corruption'] == highest_corruption_level]

# The most robust model is the one with the highest test_mean at the highest corruption level
most_robust_model_config = high_corruption_results.loc[high_corruption_results['test_mean'].idxmax()]

print(f"Most Robust Model Configuration at {highest_corruption_level*100:.0f}% Corruption:")
print(f"  Model: {most_robust_model_config['model']}")
print(f"  C value: {most_robust_model_config['C']}")
print(f"  k value: {int(most_robust_model_config['k'])}")
print(f"  Mean Test Accuracy: {most_robust_model_config['test_mean']:.4f}")
print(f"  Std Dev Test Accuracy: {most_robust_model_config['test_std']:.4f}")

"""more corruption --> increased varience"""

# Test accuracy variance
plt.figure(figsize=(12, 7))

sns.lineplot(
    data=df,
    x='corruption',
    y='test_std',
    hue='model',
    style='C',
    marker='o'
)

plt.title('Test Accuracy Variance vs. Corruption ')
plt.xlabel('Corruption Level')
plt.ylabel('Std Dev of Test Accuracy')
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

# Gap variance
plt.figure(figsize=(12, 7))

sns.lineplot(
    data=df,
    x='corruption',
    y='gap_std',
    hue='model',
    style='C',
    marker='o'
)

plt.title('Train-Test Gap Variance vs. Corruption ')
plt.xlabel('Corruption Level')
plt.ylabel('Std Dev of Gap')
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

for model in models:
    for C in C_values:
        plot_heatmap(df, model, C, "test_std",
             f"{model} (C={C}) Test Variance ")

        plot_heatmap(df, model, C, "gap_std",
             f"{model} (C={C}) Gap Variance ")

low_var = df[df["corruption"] == 0.0]["test_std"].mean()
high_var = df[df["corruption"] == max(corruption_levels)]["test_std"].mean()

print(f"Variance at 0% corruption: {low_var:.4f}")
print(f"Variance at max corruption: {high_var:.4f}")

aggregated_results = df.groupby(['model', 'C', 'k']).agg(
    overall_avg_test_mean=('test_mean', 'mean'),
    overall_avg_test_std=('test_std', 'mean') # Also average the std dev for context
).reset_index()

# Find the configuration with the highest overall average test accuracy
most_robust_overall_config = aggregated_results.loc[aggregated_results['overall_avg_test_mean'].idxmax()]

print(f"Most Robust Model Configuration (Overall Average Test Accuracy):")
print(f"  Model: {most_robust_overall_config['model']}")
print(f"  C value: {most_robust_overall_config['C']}")
print(f"  k value: {int(most_robust_overall_config['k'])}")
print(f"  Overall Average Test Accuracy: {most_robust_overall_config['overall_avg_test_mean']:.4f}")
print(f"  Overall Average Test Accuracy Std Dev: {most_robust_overall_config['overall_avg_test_std']:.4f}")

print("Baseline accuracy for (1,6):")
clf_1_6 = baseline(d1=1, d2=6, model="LogReg", C=1.0)

print("\nBaseline accuracy for (3,8):")
clf_3_8 = baseline(d1=3, d2=8, model="LogReg", C=1.0)

k_values = [5, 10, 20]
corruption_levels = [0.0, 0.1, 0.2, 0.3, 0.4]
models = ["SVM", "LogReg"]

iterations = 100
C = 1.0

for model in models:
    for corruption in corruption_levels:
        for k in k_values:

            train_accs, test_accs = track_iterations(
                d1=1,
                d2=6,
                k=k,
                iterations=iterations,
                model=model,
                C=C,
                corruption=corruption
            )

            plt.figure(figsize=(10, 6))
            plt.plot(range(iterations), train_accs, label="Training Accuracy")
            plt.plot(range(iterations), test_accs, label="Test Accuracy")

            plt.xlabel("Iteration")
            plt.ylabel("Accuracy")
            plt.title(f"{model} | k={k} | corruption={corruption}")
            plt.legend()
            plt.grid(True)
            plt.ylim(0, 1)

            plt.show()
